# Generated by Django 5.0.1 on 2024-01-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='payment_type',
            field=models.CharField(choices=[('naqd', 'naqd'), ('karta', 'karta')], default='naqd', max_length=128),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
