# Generated by Django 5.0.1 on 2024-01-30 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patients_amount_patients_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('payment_type', models.CharField(choices=[('naqd', 'naqd'), ('karta', 'karta')], default='naqd', max_length=128)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patients')),
            ],
        ),
    ]
