# Generated by Django 5.0.1 on 2024-01-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_patients_amount_remove_patients_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.patients'),
        ),
    ]
